"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("clientApi", {
  getSettings: () => ipcRenderer.invoke("client:get-settings"),
  continueFree: () => ipcRenderer.invoke("client:continue-free"),
  importStableSettings: () => ipcRenderer.invoke("client:import-stable-settings"),
  getRuntimeConfig: () => ipcRenderer.invoke("runtime-config:get"),
  saveSettings: (settings) => ipcRenderer.invoke("client:save-settings", settings),
  loginVrchatAccount: (credentials) => ipcRenderer.invoke("vrchat:account-login", credentials),
  verifyVrchatAccount: (payload) => ipcRenderer.invoke("vrchat:account-verify", payload),
  cancelVrchatAccountLogin: () => ipcRenderer.invoke("vrchat:account-cancel"),
  disconnectVrchatAccount: () => ipcRenderer.invoke("vrchat:account-disconnect"),
  getVrchatCurrentUser: () => ipcRenderer.invoke("vrchat:current-user"),
  getVrchatCurrentInstance: () => ipcRenderer.invoke("vrchat:current-instance"),
  getVrchatSocialSummary: (force = false) => ipcRenderer.invoke("vrchat:social-summary", force),
  getVrchatUserProfile: (userId) => ipcRenderer.invoke("vrchat:user-profile", userId),
  getVrchatGroup: (groupId) => ipcRenderer.invoke("vrchat:group", groupId),
  getVrchatPersonalCollection: (kind, force = false) => ipcRenderer.invoke("vrchat:personal-collection", kind, force),
  activate: (body) => ipcRenderer.invoke("client:activate", body),
  validate: () => ipcRenderer.invoke("client:validate"),
  logout: () => ipcRenderer.invoke("client:logout"),
  startTail: (options) => ipcRenderer.invoke("tail:start", options),
  updatePlaySession: (stats) => ipcRenderer.invoke("tail:update-session", stats),
  stopTail: (stats) => ipcRenderer.invoke("tail:stop", stats),
  listPlaySessions: () => ipcRenderer.invoke("play-sessions:list"),
  searchCompanion: (query) => ipcRenderer.invoke("companion:search", query),
  getCompanionDetails: (kind, key) => ipcRenderer.invoke("companion:details", kind, key),
  saveLocalPlayerPreference: (preference) => ipcRenderer.invoke("companion:save-player-preference", preference),
  listLocalWatchedPlayers: () => ipcRenderer.invoke("companion:list-watched-players"),
  listLocalSocialEvents: (limit = 500) => ipcRenderer.invoke("companion:social-events", limit),
  getFriendPipelineStatus: () => ipcRenderer.invoke("companion:friend-pipeline-status"),
  refreshFriendFeed: () => ipcRenderer.invoke("companion:refresh-friend-feed"),
  onSocialActivity: (handler) => ipcRenderer.on("companion:social-activity", (_event, payload) => handler(payload)),
  onFriendPipelineStatus: (handler) => ipcRenderer.on("companion:friend-pipeline-status", (_event, payload) => handler(payload)),
  saveLocalWorldPreference: (preference) => ipcRenderer.invoke("companion:save-world-preference", preference),
  getLocalStorageStats: () => ipcRenderer.invoke("companion:storage-stats"),
  clearLocalDataCategory: (category) => ipcRenderer.invoke("companion:clear-category", category),
  setLocalRetention: (days) => ipcRenderer.invoke("companion:set-retention", days),
  exportLocalData: (uiSettings) => ipcRenderer.invoke("companion:export", uiSettings),
  importLocalData: () => ipcRenderer.invoke("companion:import"),
  saveTextFile: (options) => ipcRenderer.invoke("file:save-text", options),
  listPlayerNotes: () => ipcRenderer.invoke("player-notes:list"),
  savePlayerNote: (note) => ipcRenderer.invoke("player-notes:save", note),
  listGlobalPlayerNotes: () => ipcRenderer.invoke("global-player-notes:list"),
  saveGlobalPlayerNote: (note) => ipcRenderer.invoke("global-player-notes:save", note),
  removeGlobalPlayerNote: (userId) => ipcRenderer.invoke("global-player-notes:remove", userId),
  requestGroupBan: (request) => ipcRenderer.invoke("moderation:request-group-ban", request),
  requestGroupUnban: (request) => ipcRenderer.invoke("moderation:request-group-unban", request),
  listGroupBanRequests: () => ipcRenderer.invoke("moderation:list-group-ban-requests"),
  updateModerationAppeal: (request) => ipcRenderer.invoke("moderation:update-appeal", request),
  retryGroupBanRequest: (requestId) => ipcRenderer.invoke("moderation:retry-group-ban-request", requestId),
  requestGroupManagement: (request) => ipcRenderer.invoke("group-management:request", request),
  listGroupManagementRequests: () => ipcRenderer.invoke("group-management:list-requests"),
  listPlayerNoteHistory: (userId) => ipcRenderer.invoke("player-notes:history", userId),
  listAvatarCatalog: () => ipcRenderer.invoke("avatar-catalog:list"),
  saveAvatarCatalog: (entry) => ipcRenderer.invoke("avatar-catalog:save", entry),
  listAvatarNotes: () => ipcRenderer.invoke("avatar-notes:list"),
  saveAvatarNote: (note) => ipcRenderer.invoke("avatar-notes:save", note),
  listGlobalAvatarNotes: () => ipcRenderer.invoke("global-avatar-notes:list"),
  saveGlobalAvatarNote: (note) => ipcRenderer.invoke("global-avatar-notes:save", note),
  removeGlobalAvatarNote: (avatarId) => ipcRenderer.invoke("global-avatar-notes:remove", avatarId),
  resolveVrchatAvatar: (avatarId) => ipcRenderer.invoke("vrchat:avatar", avatarId),
  findVrchatAvatarCandidates: (avatarName) => ipcRenderer.invoke("vrchat:avatar-search", avatarName),
  searchVrchatAvatars: (searchText) => ipcRenderer.invoke("vrchat:avatar-browse", searchText),
  favoriteVrchatAvatar: (avatarId) => ipcRenderer.invoke("vrchat:avatar-favorite", avatarId),
  selectVrchatAvatar: (avatarId) => ipcRenderer.invoke("vrchat:avatar-select", avatarId),
  getCrashStatus: (options) => ipcRenderer.invoke("crash:status", options),
  prepareAnalyzeOptions: (options) => ipcRenderer.invoke("tail:prepare-analysis-options", options),
  analyzeCurrentInstance: (options) => ipcRenderer.invoke("tail:analyze-current-instance", options),
  readTodayPlayers: () => ipcRenderer.invoke("tail:read-today-players"),
  latestFile: () => ipcRenderer.invoke("tail:latest-file"),
  chooseFile: () => ipcRenderer.invoke("tail:choose-file"),
  writeClipboardText: (text) => ipcRenderer.invoke("clipboard:write-text", text),
  showNotification: (payload) => ipcRenderer.invoke("notification:show", payload),
  openExternal: (url) => ipcRenderer.invoke("shell:open", url),
  setAlwaysOnTop: (enabled, opacity) => ipcRenderer.invoke("window:set-always-on-top", enabled, opacity),
  setWindowOpacity: (opacity) => ipcRenderer.invoke("window:set-opacity", opacity),
  setCompactMode: (enabled) => ipcRenderer.invoke("window:set-compact", enabled),
  installUpdate: () => ipcRenderer.invoke("updater:install-now"),
  onLogEvent: (handler) => ipcRenderer.on("log:event", (_event, payload) => handler(payload)),
  onTailStatus: (handler) => ipcRenderer.on("tail:status", (_event, payload) => handler(payload)),
  onTailRotation: (handler) => ipcRenderer.on("tail:rotation", (_event, payload) => handler(payload)),
  onTailError: (handler) => ipcRenderer.on("tail:error", (_event, payload) => handler(payload)),
  onAnalysisStart: (handler) => ipcRenderer.on("analysis:start", (_event, payload) => handler(payload)),
  onAuthStatus: (handler) => ipcRenderer.on("auth:status", (_event, payload) => handler(payload)),
  onUserResolved: (handler) => ipcRenderer.on("user:resolved", (_event, payload) => handler(payload)),
  onUpdaterStatus: (handler) => ipcRenderer.on("updater:status", (_event, payload) => handler(payload)),
  onRuntimeConfig: (handler) => ipcRenderer.on("runtime-config:updated", (_event, payload) => handler(payload))
});
