"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("clientApi", {
  getSettings: () => ipcRenderer.invoke("client:get-settings"),
  saveSettings: (settings) => ipcRenderer.invoke("client:save-settings", settings),
  getVrchatCurrentUser: () => ipcRenderer.invoke("vrchat:current-user"),
  getVrchatCurrentInstance: () => ipcRenderer.invoke("vrchat:current-instance"),
  activate: (body) => ipcRenderer.invoke("client:activate", body),
  validate: () => ipcRenderer.invoke("client:validate"),
  logout: () => ipcRenderer.invoke("client:logout"),
  startTail: (options) => ipcRenderer.invoke("tail:start", options),
  updatePlaySession: (stats) => ipcRenderer.invoke("tail:update-session", stats),
  stopTail: (stats) => ipcRenderer.invoke("tail:stop", stats),
  listPlaySessions: () => ipcRenderer.invoke("play-sessions:list"),
  listPlayerNotes: () => ipcRenderer.invoke("player-notes:list"),
  savePlayerNote: (note) => ipcRenderer.invoke("player-notes:save", note),
  listGlobalPlayerNotes: () => ipcRenderer.invoke("global-player-notes:list"),
  saveGlobalPlayerNote: (note) => ipcRenderer.invoke("global-player-notes:save", note),
  removeGlobalPlayerNote: (userId) => ipcRenderer.invoke("global-player-notes:remove", userId),
  listPlayerNoteHistory: (userId) => ipcRenderer.invoke("player-notes:history", userId),
  listAvatarCatalog: () => ipcRenderer.invoke("avatar-catalog:list"),
  saveAvatarCatalog: (entry) => ipcRenderer.invoke("avatar-catalog:save", entry),
  listAvatarNotes: () => ipcRenderer.invoke("avatar-notes:list"),
  saveAvatarNote: (note) => ipcRenderer.invoke("avatar-notes:save", note),
  resolveVrchatAvatar: (avatarId) => ipcRenderer.invoke("vrchat:avatar", avatarId),
  findVrchatAvatarCandidates: (avatarName) => ipcRenderer.invoke("vrchat:avatar-search", avatarName),
  getCrashStatus: (options) => ipcRenderer.invoke("crash:status", options),
  prepareAnalyzeOptions: (options) => ipcRenderer.invoke("tail:prepare-analysis-options", options),
  analyzeCurrentInstance: (options) => ipcRenderer.invoke("tail:analyze-current-instance", options),
  latestFile: () => ipcRenderer.invoke("tail:latest-file"),
  chooseFile: () => ipcRenderer.invoke("tail:choose-file"),
  writeClipboardText: (text) => ipcRenderer.invoke("clipboard:write-text", text),
  showNotification: (payload) => ipcRenderer.invoke("notification:show", payload),
  openExternal: (url) => ipcRenderer.invoke("shell:open", url),
  setAlwaysOnTop: (enabled, opacity) => ipcRenderer.invoke("window:set-always-on-top", enabled, opacity),
  setWindowOpacity: (opacity) => ipcRenderer.invoke("window:set-opacity", opacity),
  setCompactMode: (enabled) => ipcRenderer.invoke("window:set-compact", enabled),
  installUpdate: () => ipcRenderer.invoke("updater:install-now"),
  onLogEvent: (handler) => ipcRenderer.on("log:event", (_event, payload) => handler(payload)),
  onTailStatus: (handler) => ipcRenderer.on("tail:status", (_event, payload) => handler(payload)),
  onTailRotation: (handler) => ipcRenderer.on("tail:rotation", (_event, payload) => handler(payload)),
  onTailError: (handler) => ipcRenderer.on("tail:error", (_event, payload) => handler(payload)),
  onAnalysisStart: (handler) => ipcRenderer.on("analysis:start", (_event, payload) => handler(payload)),
  onAuthStatus: (handler) => ipcRenderer.on("auth:status", (_event, payload) => handler(payload)),
  onUserResolved: (handler) => ipcRenderer.on("user:resolved", (_event, payload) => handler(payload)),
  onUpdaterStatus: (handler) => ipcRenderer.on("updater:status", (_event, payload) => handler(payload))
});
